name: Tom Blockley
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49877
title: Tom Blockley - Designer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76279114-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#263959'
    - '#854f2d'
    - '#db893d'
    - '#ffffdc'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
