name: Tom Blockley
favicon: null
layout_spectrum: 0.25174
typography_spectrum: 0.13855
title: Tom Blockley - Designer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76279114-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#19100b'
    - '#4b6363'
    - '#c1976f'
    - '#e5c5a8'
  brandStrength: 1
  lightness: 0
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
